export const MQTT_CLIENT = 'MQTT_CLIENT'

export const ENV = {
  MQTT_PROTOCOL: 'MQTT_PROTOCOL',
  MQTT_HOST: 'MQTT_HOST',
  MQTT_PORT: 'MQTT_PORT',
  MQTT_CLIENT_ID: 'MQTT_CLIENT_ID',
  MQTT_USERNAME: 'MQTT_USERNAME',
  MQTT_PASSWORD: 'MQTT_PASSWORD',
}